---
version: '3'
services:
  panther:
    image: pantherorg/panther:stable
    # image: pantherorg/panther:develop
    # Use plotting image
    # image: pantherorg/panther:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: panther
    volumes:
      - "./user_data:/panther/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.panther.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /panther/user_data/logs/panther.log
      --db-url sqlite:////panther/user_data/tradesv3.sqlite
      --config /panther/user_data/config.json
      --strategy SampleStrategy
